### ISSUE TITLE
Build article component

### ISSUE THREAD

**Issue by sjmog** [makersacademy/components#62]
For extended text. We need to discuss how best to go about rendering this (passing in a Markdown file seems easiest, and linking the Markdown file in the YAML)

Wireframe: https://makersacademy.mybalsamiq.com/projects/newsitewireframes/article

Required for #9.

**Comment by sjmog** [comment]
Sample YAML for this:

```yaml
- template: article
  - title: Lorem Ipsum (optional)
  - subtitle: Dolor Sit Amet (optional)
  - body: Lots of words here is my body _here is some italics_ and **here is some bold**
  - blockquote: Testimonial Ipsum Dolor, Sit Amet Adipscing Elit (optional)
```

Articles require a body, but all other aspects are optional. Blockquotes are always placed at the bottom of an Article block.
